#Service name
server:
  port: 2225

spring:
  application:
   name: apiservice

# Discovery Server Access

eureka:
  instance:
    health-check-url: /health
    status-page-url-path: /info
    instance-enabled-onit: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3

  client:
   registerWithEureka: true
   fetchRegistry: true
   healthcheck:
    enabled: true
   serviceUrl:
     defaultZone: http://localhost:1111/eureka/
   dashboard:
    enabled: false
