
#Service name
server:
<<<<<<< HEAD
  port: 2227
=======
  port: 2240
>>>>>>> 5d60878f1c969aaff838a3697a97106c9d5e9476

spring:
  application:
   name: demoservice


  cloud:
    config:
      discovery:
        enabled: true
eureka:
  instance:
    health-che ck-url: /health
    status-page-url-path: /info
    instance-enabled-onit: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3

  client:
   registerWithEureka: true
   fetchRegistry: true
   healthcheck:
    enabled: true
   serviceUrl:
     defaultZone: http://localhost:1111/eureka/
   dashboard:
    enabled: false

#  server:
#   renewalPercentThreshold: 0.0
#   enableSelfPreservation: false
#   waitTimeInMsWhenSyncEmpty: 0

#endpoints:
#  refresh:
#    enabled: true
#  restart:
#    enabled: true
